export const BOARD_DATA={
    pages:[
        {
            postsResponses: [
                {
                    title: '내일 월요일 실화냐!!!!!!',
                    createdDate: '2022.11.20 19:52',
                    postId: 9999,
                    likeCount: 3,
                    commentCount: 0,
                },
                {
                    title: '다음주 식단표 업뎃 언제 되나요',
                    createdDate: '2022.11.20 19:19',
                    postId: 9998,
                    likeCount: 0,
                    commentCount: 2,
                },
                {
                    title: '8기 있나요?',
                    createdDate: '2022.11.20 18:29',
                    postId: 9997,
                    likeCount: 1,
                    commentCount: 4,
                },
                {
                    title: '다들 맛저~',
                    createdDate: '2022.11.20 18:20',
                    postId: 9996,
                    likeCount: 1,
                    commentCount: 4,
                },
                {
                    title: '클라이밍 후기',
                    createdDate: '2022.11.20 17:48',
                    postId: 9995,
                    likeCount: 1,
                    commentCount: 2,
                },
                {
                    title: '핫게가고 싶어요',
                    createdDate: '2022.11.20 17:46',
                    postId: 9994,
                    likeCount: 4,
                    commentCount: 1,
                },
                {
                    title: '안녕하세요',
                    createdDate: '2022.11.20 17:21',
                    postId: 9993,
                    likeCount: 0,
                    commentCount: 0,
                },
                {
                    title: '모두 자유 프로젝트 화이팅!',
                    createdDate: '2022.11.20 17:19',
                    postId: 9992,
                    likeCount: 3,
                    commentCount: 3,
                },
                {
                    title: '뭔지 맞춰보기',
                    createdDate: '2022.11.20 16:58',
                    postId: 9991,
                    likeCount: 0,
                    commentCount: 1,
                },
                {
                    title: '안녕하세요',
                    createdDate: '2022.11.20 15:46',
                    postId: 9990,
                    likeCount: 1,
                    commentCount: 2,
                },
                {
                    title: 'iNSSA 화이팅!',
                    createdDate: '2022.11.20 14:21',
                    postId: 9989,
                    likeCount: 6,
                    commentCount: 6,
                },
                {
                    title: '점심시간 곧 끝난다',
                    createdDate: '2022.11.20 12:59',
                    postId: 9988,
                    likeCount: 0,
                    commentCount: 0,
                },
                {
                    title: '모두들 산책을 나갑시다',
                    createdDate: '2022.11.20 12:30',
                    postId: 9987,
                    likeCount: 3,
                    commentCount: 0,
                },
                {
                    title: '오늘 점심 존맛!',
                    createdDate: '2022.11.20 12:15',
                    postId: 9986,
                    likeCount: 0,
                    commentCount: 0,
                },
                {
                    title: '여기까지가 첫번째 데이터의 끝!',
                    createdDate: '2022.11.20 12:14',
                    postId: 9985,
                    likeCount: 0,
                    commentCount: 0,
                }
            ],
            last:true,
        },
    ]
}

export const FULL_BOARD_DATA=[
    {
        postsResponses: [
            {
                title: '새로운 게시판 목록이 추가되었습니다.',
                createdDate: '2022.11.20 12:13',
                postId: 9984,
                likeCount: 0,
                commentCount: 0,
            },
            {
                title: '모두들 맛점!',
                createdDate: '2022.11.20 12:00',
                postId: 9983,
                likeCount: 3,
                commentCount: 0,
            },
            {
                title: '점심시간 5분전!',
                createdDate: '2022.11.20 11:55',
                postId: 9982,
                likeCount: 0,
                commentCount: 0,
            },
            {
                title: '아 배고파',
                createdDate: '2022.11.20 11:48',
                postId: 9981,
                likeCount: 3,
                commentCount: 1,
            },
            {
                title: '아 너무 힘들다',
                createdDate: '2022.11.20 11:46',
                postId: 9980,
                likeCount: 0,
                commentCount: 3,
            },
            {
                title: '얼른 취업하고싶다',
                createdDate: '2022.11.20 11:38',
                postId: 9979,
                likeCount: 5,
                commentCount: 2,
            },
            {
                title: '오늘 같이 저녁먹을사람~',
                createdDate: '2022.11.20 11:12',
                postId: 9978,
                likeCount: 0,
                commentCount: 2,
            },
            {
                title: '오늘 할일 너무 많다ㅠㅠ',
                createdDate: '2022.11.20 10:48',
                postId: 9977,
                likeCount: 3,
                commentCount: 0,
            },
            {
                title: '모두들 어디야?',
                createdDate: '2022.11.20 09:59',
                postId: 9976,
                likeCount: 0,
                commentCount: 2,
            },
            {
                title: '공부하러 나가는중...',
                createdDate: '2022.11.20 09:48',
                postId: 9975,
                likeCount: 0,
                commentCount: 0,
            },
            {
                title: '오늘도 힘내서 화이팅!',
                createdDate: '2022.11.20 09:34',
                postId: 9974,
                likeCount: 3,
                commentCount: 6,
            },
            {
                title: '와 일요일에 이렇게 일찍 일어난건 처음이네',
                createdDate: '2022.11.20 09:32',
                postId: 9973,
                likeCount: 2,
                commentCount: 1,
            },
            {
                title: '좋은아침!',
                createdDate: '2022.11.20 08:24',
                postId: 9972,
                likeCount: 0,
                commentCount: 0,
            },
            {
                title: '추가된 게시글 목록이 끝났습니다.',
                createdDate: '2022.11.20 08:22',
                postId: 9971,
                likeCount: 0,
                commentCount: 0,
            },
        ],
        last:false,
    },
    {
        postsResponses: [
            {
                title: '안녕하세요',
                createdDate: '2022.08.08',
                postId: 0,
                likeCount: 15,
                commentCount: 8,
            }
        ],
        last:true,
    },
];
